removed git cloning + added backward compatibility

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -1,17 +1,23 @@
 name: 'TruffleHog OSS'
-description: 'Scan for secrets in Github Actions with TruffleHog.'
+description: 'Scan Github Actions with TruffleHog.'
 author: Truffle Security Co. <support@trufflesec.com>
 
 inputs:
-  full_repo:
-    default: false
-    description: Run a TruffleHog scan against the entire repository.
+  path:
+    description: Repository path
     required: false
-  extra_truffle_args:
+    default: "./"
+  base:
+    description: Start scanning from here (usually main branch).
+    required: false
+    default: ''
+  head:
+    description: Scan commits until here (usually dev branch).
+    required: false
+  extra_args:
     default: ''
     description: Extra args to be passed to the trufflehog cli.
     required: false
-
 branding:
   icon: "shield"
   color: "green"
@@ -19,60 +25,68 @@ branding:
 runs:
   using: "composite"
   steps:
-      ###########################
-      ## SHALLOW CLONING STEPS ##
-      ###########################
-      ## Get count of commits in Push or PR and target branch.
-      - shell: bash
-        run: |
-          if [ "${{ github.event_name }}" == "push" ]; then
-            echo "depth=$(($(jq length <<< '${{ toJson(github.event.commits) }}') + 1))" >> $GITHUB_ENV
-            echo "branch=${{ github.ref_name }}" >> $GITHUB_ENV
+  - shell: bash
+    env:
+      REPO_PATH: ${{ inputs.path }}
+      BASE: ${{ inputs.base }}
+      HEAD: ${{ inputs.head }}
+      ARGS: ${{ inputs.extra_args }}
+    run: |
+      ##########################################
+      ## ADVANCED USAGE                       ##
+      ## Scan by BASE & HEAD user inputs      ##
+      ## If BASE == HEAD, exit with error     ##
+      ##########################################
+      if [ -n "$BASE" ] || [ -n "$HEAD" ]; then
+        if [ -n "$BASE" ]; then
+          base_commit=$(git rev-parse "$BASE" 2>/dev/null) || true
+        else
+          base_commit=""
+        fi
+        if [ -n "$HEAD" ]; then
+          head_commit=$(git rev-parse "$HEAD" 2>/dev/null) || true
+        else
+          head_commit=""
+        fi
+        if [ $base_commit == $head_commit ] ; then
+          echo "::error::BASE and HEAD commits are the same. TruffleHog won't scan anything. Please see documentation (https://github.com/trufflesecurity/trufflehog#octocat-trufflehog-github-action)."
+          exit 1
+        fi
+      ##########################################
+      ## Scan commits based on event type     ##
+      ##########################################
+      else
+        if [ "${{ github.event_name }}" == "push" ]; then
+          COMMIT_LENGTH=$(jq length <<< '${{ toJson(github.event.commits) }}')
+          if [ $COMMIT_LENGTH == "0" ]; then
+            echo "No commits to scan"
+            exit 0
           fi
-          if [ "${{ github.event_name }}" == "pull_request" ]; then
-            echo "depth=$((${{ github.event.pull_request.commits }}+1))" >> $GITHUB_ENV
-            echo "branch=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV
+          HEAD=${{ github.event.after }}
+          if [ ${{ github.event.before }} == "0000000000000000000000000000000000000000" ]; then
+            BASE=$(git rev-parse $HEAD~$COMMIT_LENGTH)
+          else
+            BASE=${{ github.event.before }}
           fi
-        id: set_values
-        if: ${{ inputs.full_repo == 'false' }}
-
-      ## Checkout code with --depth and --branch args from the step above
-      - uses: actions/checkout@v3
-        with:
-          ref: ${{env.branch}}
-          fetch-depth: ${{env.depth}}
-        if: ${{ inputs.full_repo == 'false' }}
-
-      ## Get the base commit from the shallow clone and set as env var since_commit
-      - shell: bash
-        run: echo "since_commit=$(git rev-list --max-parents=0 HEAD)" >> $GITHUB_ENV
-        if: ${{ inputs.full_repo == 'false' }}
-
-      ###########################
-      ## FULL REPO SCAN STEPS  ##
-      ###########################
-      ## Clone full repo
-      - uses: actions/checkout@v3
-        with:
-          fetch-depth: 0
-        if: ${{ inputs.full_repo == 'true' }}
-
-      ## Set since_commit env var to empty string (so it will scan the entire repo)
-      - shell: bash
-        run: echo "since_commit=''" >> $GITHUB_ENV
-        if: ${{ inputs.full_repo == 'true' }}
-
-      ################################
-      ## SCAN REPO WITH TRUFFLEHOG  ##
-      ################################
-      ## Pass in the env var since_commit derived in a prior step + any extra truffle args
-      - shell: bash
-        run: |
-          docker run --rm -v "$(pwd)":/tmp \
-          ghcr.io/trufflesecurity/trufflehog:latest \
-          git file:///tmp/ \
-          --since-commit ${{env.since_commit}} \
-          --fail \
-          --no-update \
-          --github-actions \
-          ${{ inputs.extra_truffle_args }}
+        elif [ "${{ github.event_name }}" == "workflow_dispatch" ] || [ "${{ github.event_name }}" == "schedule" ]; then
+          BASE=""
+          HEAD=""
+        elif [ "${{ github.event_name }}" == "pull_request" ]; then
+          BASE=${{github.event.pull_request.base.sha}}
+          HEAD=${{github.event.pull_request.head.sha}}
+        fi
+      fi
+      ##########################################
+      ##          Run TruffleHog              ##
+      ##########################################       
+      docker run --rm -v "$REPO_PATH":/tmp \
+      ghcr.io/trufflesecurity/trufflehog:latest \
+      git file:///tmp/ \
+      --since-commit \
+      ${BASE:-''} \
+      --branch \
+      ${HEAD:-''} \
+      --fail \
+      --no-update \
+      --github-actions \
+      ${ARGS:-''}
