add buildpulse config to sources

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -66,5 +66,27 @@ jobs:
         go-version: '1.21'
     - name: Checkout code
       uses: actions/checkout@v3
-    - name: Test
-      run: make test-community
+    - name: Set up gotestsum
+      run: |
+        go install gotest.tools/gotestsum@latest
+        mkdir -p tmp/test-results
+    - name: Test 
+      run: |
+	CGO_ENABLED=0 go test -timeout=5m $(shell go list ./... | grep -v /vendor/ | grep -v pkg/detectors | grep -v 'pkg/sources')
+      if: ${{ success() || failure() }} # always run this step, even if there were previous errors
+    - name: Upload test results to BuildPulse for flaky test detection
+      if: '!cancelled()' # Run this step even when the tests fail. Skip if the workflow is cancelled.
+      uses: buildpulse/buildpulse-action@main
+      with:
+        account: 79229934
+        repository: 523156419
+        path: |
+          tmp/test-results/*.xml
+        key: ${{ secrets.BUILDPULSE_ACCESS_KEY_ID }}
+        secret: ${{ secrets.BUILDPULSE_SECRET_ACCESS_KEY }}
+        tags: scanner
+    - name: Annotate test results
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'tmp/test-results/*.xml'
